### ISSUE TITLE
Compile in ESP32-IDF?

### ISSUE THREAD

**Issue by N9SHazpnhYW** [kmwebnet/ECC608-simple-Connection-Test-idf42#1]
I would like to use this example in another large program written for the ESP-IDF compiler.  Would you happen to know how I can compile this using ESP-IDF instead of PlatformIO?

**Comment by cyberomusubi** [comment]
for the reference, please also check esp-idf implementation, as follows.
[ECC608-Simple-Connection-Test-idf42-2](https://github.com/kmwebnet/ECC608-Simple-Connection-Test-idf42-2)

**Comment by N9SHazpnhYW** [comment]
thanks for the reply!  i managed to figure it out
